export const SET_FILE_NAME = "SET_FILE_NAME";
export const TOGGLE_TITLE_AND_MENU_WRAP = "TOGGLE_TITLE_AND_MENU_WRAP";
export const SET_SETTING_INDEX = "SET_SETTING_INDEX";
export const CHANGE_CURRENT_FONT_SIZE_INDEX = "CHANGE_CURRENT_FONT_SIZE_INDEX";